(function() {var implementors = {};
implementors["elastic"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"elastic/error/enum.Error.html\" title=\"enum elastic::error::Error\">Error</a>",synthetic:false,types:["elastic::error::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"elastic/error/struct.ClientError.html\" title=\"struct elastic::error::ClientError\">ClientError</a>",synthetic:false,types:["elastic::error::ClientError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"elastic/client/sender/static_nodes/enum.StrategyError.html\" title=\"enum elastic::client::sender::static_nodes::StrategyError\">StrategyError</a>",synthetic:false,types:["elastic::client::sender::static_nodes::StrategyError"]},];
implementors["elastic_responses"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"elastic_responses/error/struct.ParseError.html\" title=\"struct elastic_responses::error::ParseError\">ParseError</a>",synthetic:false,types:["elastic_responses::error::ParseError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"elastic_responses/error/enum.ResponseError.html\" title=\"enum elastic_responses::error::ResponseError\">ResponseError</a>",synthetic:false,types:["elastic_responses::error::ResponseError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"elastic_responses/error/enum.ApiError.html\" title=\"enum elastic_responses::error::ApiError\">ApiError</a>",synthetic:false,types:["elastic_responses::error::ApiError"]},{text:"impl&lt;TIndex, TType, TId&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"elastic_responses/bulk/struct.ErrorItem.html\" title=\"struct elastic_responses::bulk::ErrorItem\">ErrorItem</a>&lt;TIndex, TType, TId&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;TIndex: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a>,<br>&nbsp;&nbsp;&nbsp;&nbsp;TType: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a>,<br>&nbsp;&nbsp;&nbsp;&nbsp;TId: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a>,&nbsp;</span>",synthetic:false,types:["elastic_responses::bulk::ErrorItem"]},];
implementors["elastic_types"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"elastic_types/date/struct.ParseError.html\" title=\"struct elastic_types::date::ParseError\">ParseError</a>",synthetic:false,types:["elastic_types::date::format::ParseError"]},];
implementors["elastic_types_derive_internals"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"elastic_types_derive_internals/elastic_type/enum.DeriveElasticTypeError.html\" title=\"enum elastic_types_derive_internals::elastic_type::DeriveElasticTypeError\">DeriveElasticTypeError</a>",synthetic:false,types:["elastic_types_derive_internals::elastic_type::DeriveElasticTypeError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"elastic_types_derive_internals/date_format/enum.DeriveDateFormatError.html\" title=\"enum elastic_types_derive_internals::date_format::DeriveDateFormatError\">DeriveDateFormatError</a>",synthetic:false,types:["elastic_types_derive_internals::date_format::DeriveDateFormatError"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
