(function() {var implementors = {};
implementors["elastic"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>&gt; for <a class=\"struct\" href=\"elastic/client/sender/struct.NodeAddress.html\" title=\"struct elastic::client::sender::NodeAddress\">NodeAddress</a>",synthetic:false,types:["elastic::client::sender::NodeAddress"]},];
implementors["elastic_types"] = [{text:"impl&lt;TMapping&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>&gt; for <a class=\"struct\" href=\"elastic_types/string/struct.Keyword.html\" title=\"struct elastic_types::string::Keyword\">Keyword</a>&lt;TMapping&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;TMapping: <a class=\"trait\" href=\"elastic_types/string/keyword/mapping/trait.KeywordMapping.html\" title=\"trait elastic_types::string::keyword::mapping::KeywordMapping\">KeywordMapping</a>,&nbsp;</span>",synthetic:false,types:["elastic_types::string::keyword::impls::Keyword"]},{text:"impl&lt;TMapping&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>&gt; for <a class=\"struct\" href=\"elastic_types/string/struct.Text.html\" title=\"struct elastic_types::string::Text\">Text</a>&lt;TMapping&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;TMapping: <a class=\"trait\" href=\"elastic_types/string/text/mapping/trait.TextMapping.html\" title=\"trait elastic_types::string::text::mapping::TextMapping\">TextMapping</a>,&nbsp;</span>",synthetic:false,types:["elastic_types::string::text::impls::Text"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
